# Generated by Django 3.2.9 on 2021-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfrollapp', '0003_savedgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgame',
            name='player_count',
            field=models.IntegerField(default=7),
        ),
    ]
